services:
  db:
    image: mysql:5.7
    container_name: db_pet_friend
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sgdb_pet_friend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
  
  www:
      build: docker
      container_name: www_pet_friend
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ./docker/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www/html
      networks:
        - dev
    
networks:
    dev:

volumes:
  db-data:


  

  

 